### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Habeeb-mohamed** [rborn/nativescript-i18n#26]
Language like Arabic writing pattern is Right to left. On changing language layout has to be changes.
For instance i have tabview with 3 items like news,event,menu. 
For English News should be on Left most, but for arabic news should be on right most. 
Similarly all the action items, has to be changes. 

Is there a way to handle this?

**Comment by rborn** [comment]
You might try to set the alignment of the view to right.
But I think you should open a ticket with NS because they don't seem to support all the alignments 

native iOS: https://developer.apple.com/reference/uikit/nstextalignment
while NS iOS: https://github.com/NativeScript/NativeScript/blob/84c469d61b148544bd1ef8b4f41ce689f9145754/tns-core-modules/utils/utils.ios.ts#L43-L57

The orientation that interests you is "natural"

Another thing would be for you to set it yourself for the textfields you want (which means to access the native property directly, not through setTextAlignment)

**Comment by Habeeb-mohamed** [comment]
Still it is a open issue in nativescript
https://github.com/NativeScript/NativeScript/issues/42

**Comment by rborn** [comment]
Sadly yes

**Comment by spstratis** [comment]
For android, they would also need to add support for the "Start" and "End" values which are used in style properties that deal with left and right alignments.

**Comment by rborn** [comment]
Going to close this for inactivity. Please reopen if needed. Thanks.
